Repository Mind-Garden/mind-garden, pull requests merged in 2025-02, with the labels that each got.

#41 Cn/6/delete journal entry
  src/components/journal-edit.tsx
  src/utils/supabase/dbfunctions.ts
Labels: user story

#37 cu/14/implement habit tracker
  package-lock.json
  package.json
  src/app/globals.css
  src/app/home/page.tsx
  src/app/profile/page.tsx
  src/components/attribute-icon.tsx
  src/components/data-intake-form.tsx
  src/components/delete-account.tsx
  src/components/scale-icon.tsx
  src/components/toggle-button.tsx
  src/components/ui/toggle-group.tsx
  src/components/ui/toggle.tsx
  src/lib/types.ts
  src/utils/supabase/dbfunctions.ts
  src/utils/supabase/schema.ts
Labels: user story

#45 Ap/test example using jest
  README.md
  jest.setup.ts
  package-lock.json
  package.json
  src/utils/supabase/dbfunctions.spec.ts
Labels: QA

#46 Ap/test with coverage
  README.md
  package-lock.json
  package.json
Labels: QA

#43 Cn/3/add journal prompt
  src/components/journal-entry.tsx
  src/utils/supabase/dbfunctions.ts
Labels: user story

#49 Add auth unit tests with 100% coverage
  package-lock.json
  package.json
  src/actions/auth.ts
  src/app/globals.css
  src/app/home/page.tsx
  src/app/profile/page.tsx
  src/components/delete-account.tsx
  src/components/ui/dialog.tsx
  src/utils/supabase/auth.spec.ts
Labels: QA

#51 cu/xx/standardize backdrop
  .prettierignore
  src/app/error/page.tsx
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/reset-password/page.tsx
  src/app/sleep-tracker/page.tsx
  src/components/delete-account.tsx
  src/components/journal-entry.tsx
  src/components/reset-password.tsx
  src/components/sleep-entry.tsx
  src/components/sleep-tracker-button.tsx
  src/components/toggle-button.tsx
  src/components/ui/dialog.tsx
Labels: enhancement, ui updates

#54 Create header component
  package-lock.json
  package.json
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/profile/page.tsx
  src/app/sleep-tracker/page.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/journal-button.tsx
  src/components/journal-entry.tsx
  src/components/random-prompt-card.tsx
  src/components/sleep-tracker-button.tsx
  src/components/ui/tooltip.tsx
Labels: enhancement, ui updates

#59 Mg/17/sleep tracker
  src/components/sleep-entry.tsx
  src/utils/supabase/dbfunctions.ts
Labels: enhancement, ui updates

#60 Mg/12/password change
  src/actions/auth.ts
  src/app/page.tsx
Labels: bug fix

#65 Tests completed
  src/components/sleep-entry.tsx
  src/tests/sleep-tracker.spec.ts
  src/utils/supabase/dbfunctions.ts
Labels: QA

#66 tests completed for reset password auth functions
  src/tests/auth.spec.ts
Labels: QA

#64 cu/XX/clean-up-data-intake
  src/components/data-intake/data-intake-form.tsx
  src/tests/data-intake.spec.ts
  src/utils/supabase/dbfunctions.ts
Labels: bug fix, QA

#72 Refactor name validation logic and remove unnecessary console logs in sleep tracker tests
  src/actions/auth.ts
  src/tests/sleep-tracker.spec.ts
Labels: QA

#75 Reset Password for Vercel
  src/app/page.tsx
Labels: bug fix, bug

#73 Add a new Dashboard component and rename Dashboard component to Home
  src/app/home/page.tsx
  src/components/dashboard.tsx
Labels: ui updates

#76 site url accessed through env variable
  src/app/page.tsx
Labels: bug fix

#79 Remove prettier and run npm format to fix all formatting issues
  .github/workflows/prettier.yml
  .prettierignore
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/page.tsx
  src/components/dashboard.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/journal.tsx
  src/components/sleep-entry.tsx
  src/components/ui/badge.tsx
  src/components/ui/calendar.tsx
  src/components/ui/scroll-area.tsx
  src/lib/utility.ts
  src/tests/auth.spec.ts
  src/tests/data-intake.spec.ts
  src/tests/journal.spec.ts
  src/tests/sleep-tracker.spec.ts
  src/utils/supabase/client.ts
  src/utils/supabase/dbfunctions.ts
Labels: enhancement
