Repository Mind-Garden/mind-garden, pull requests merged in 2025-03, with the labels that each got.

#100 updated readme to include notifications feature
  README.md
Labels: documentation

#99 cu/xx/refactor-server-actions
  src/actions/auth.ts
  src/actions/data-intake.ts
  src/actions/journal.ts
  src/app/daily-intake/page.tsx
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/profile/page.tsx
  src/app/sleep-tracker/page.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/journal.tsx
  src/components/random-prompt-card.tsx
  src/components/sleep-entry.tsx
  src/lib/types.ts
  src/lib/utility.ts
  src/lib/utils.ts
  src/supabase/client.ts
  src/supabase/dbfunctions.ts
  src/supabase/middleware.ts
  src/supabase/schema.ts
  src/supabase/scripts/handle_new_user.sql
  src/supabase/scripts/sync_auth_user_data.sql
  src/supabase/scripts/tables.sql
  src/supabase/server.ts
  src/tests/auth.spec.ts
  src/tests/data-intake.spec.ts
  src/tests/journal.spec.ts
  src/tests/sleep-tracker.spec.ts
  src/utils/supabase/dbfunctions.ts
Labels: enhancement

#111 Ap/time zone fix
  package-lock.json
  src/actions/data-intake.ts
  src/app/page.tsx
  src/components/data-intake/data-intake-form.tsx
Labels: bug fix

#114 Refactor date handling in TaskManager
  src/components/task-manager.tsx
  src/lib/utils.ts
Labels: bug fix

#116 Add unit tests for task actions including fetch, add, mark, delete, and extract tasks
  src/tests/tasks.spec.ts
Labels: QA

#112 cu/15/implement reminders
  .eslintrc.json
  .github/workflows/reminders.yml
  package-lock.json
  package.json
  src/actions/email.ts
  src/actions/reminders.ts
  src/app/api/cron/route.ts
  src/app/layout.tsx
  src/app/reminders/page.tsx
  src/components/dashboard.tsx
  src/components/header.tsx
  src/components/reminder-card.tsx
  src/components/ui/switch.tsx
  src/lib/email-service.ts
  src/lib/email-templates.ts
  src/lib/fonts.ts
  src/lib/time.ts
  src/supabase/schema.ts
  src/tests/cron.spec.ts
  src/tests/email-service.spec.ts
  src/tests/email.spec.ts
  src/tests/reminders.spec.ts
  tailwind.config.ts
Labels: feature, QA

#122 fixed api endpoint
  .github/workflows/reminders.yml
Labels: bug fix

#125 Mg/92/quantifiable habits
  package-lock.json
  src/actions/data-intake.ts
  src/actions/data-visualization.ts
  src/app/home/page.tsx
  src/components/bar-line-chart.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/sleep-chart.tsx
  src/components/sleep-entry.tsx
  src/components/ui/counter-card.tsx
  src/components/ui/counter.tsx
  src/components/ui/line-graph.tsx
  src/components/ui/rating-scale.tsx
  src/components/water-chart.tsx
  src/lib/utils.ts
  src/supabase/schema.ts
Labels: user story

#126 Update login page UI
  package-lock.json
  package.json
  src/app/globals.css
  src/app/page.tsx
  src/app/task-manager/page.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/magicui/typing-animation.tsx
  src/components/magicui/word-rotate.tsx
  src/components/tasks/task-manager.tsx
  src/components/tasks/voice-recorder.tsx
Labels: enhancement, ui updates

#128 Update llm-api docker to work on both cpu and gpu devices
  llm-api/docker-compose.yml
Labels: enhancement

#130 updated tests for quantifiable habits
  src/tests/data-visualization.spec.ts
Labels: QA

#121 Jr/create tests for mood chart mood flow
  llm-api/docker-compose.yml
  src/actions/ai-data-analysis.ts
  src/actions/ai-fetch.ts
  src/actions/tasks.ts
  src/app/page.tsx
  src/components/data-intake/data-intake-form.tsx
  src/lib/utils.ts
  src/tests/data-summarization.spec.tsx
  src/tests/data-visualization.spec.ts
  src/tests/lib-utils.spec.ts
Labels: QA

#132 Ap/reminders testing
  .github/workflows/docker-image.yml
  .github/workflows/reminders.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/actions/auth.ts
  src/app/page.tsx
  src/lib/email-service.ts
  src/tests/integration/cron-integration.spec.ts
  src/tests/integration/email-integration.spec.ts
  src/tests/integration/email-service-integration.spec.ts
  src/tests/integration/reminders-integration.spec.ts
Labels: QA

#133 Performed some clean up for sprint 3
  .github/workflows/test.yml
  README.md
  package.json
  src/actions/data-intake.ts
  src/app/layout.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/habit-heatmap.tsx
  src/components/water-chart.tsx
  src/lib/utility.ts
  src/tests/unit/add-data.spec.ts
  src/tests/unit/auth.spec.ts
  src/tests/unit/cron.spec.ts
  src/tests/unit/data-intake.spec.ts
  src/tests/unit/data-summarization.spec.ts
  src/tests/unit/data-visualization.spec.ts
  src/tests/unit/email-service.spec.ts
  src/tests/unit/email.spec.ts
  src/tests/unit/journal.spec.ts
  src/tests/unit/lib-utils.spec.ts
  src/tests/unit/reminders.spec.ts
  src/tests/unit/sleep-tracker.spec.ts
  src/tests/unit/tasks.spec.ts
  src/tests/unit/time.spec.ts
Labels: QA

#138 Remove hard coded uuid
  src/tests/integration/data-intake-integration.spec.ts
Labels: QA

#136 Add journal integration test
  src/tests/integration/auth-integration.spec.ts
  src/tests/integration/cron-integration.spec.ts
  src/tests/integration/journal-integration.spec.ts
  src/tests/integration/reminders-integration.spec.ts
  src/tests/integration/tasks-integration.spec.ts
Labels: QA

#140 data visualization integration tests
  package-lock.json
  src/tests/integration/data-visualization-integration.spec.ts
Labels: QA

#141 Cn/fix/heatmap key
  src/actions/data-intake.ts
  src/components/habit-heatmap.tsx
Labels: bug fix

#143 fixed sleep entry bug that caused 12pm to map to 12am
  src/components/sleep-entry.tsx
  src/lib/utils.ts
Labels: bug fix

#146 Jr/fix UI break for one entry
  src/components/ui/line-graph.tsx
Labels: bug fix

#148 Fix habit heatmap key error
  src/components/habit-heatmap.tsx
Labels: bug fix

#153 Jr/fix scroll on small viewport
  docker-compose.yml
  src/app/home/page.tsx
  src/components/ui/line-graph.tsx
Labels: bug fix

#155 Added fonts
  package-lock.json
  src/app/globals.css
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/page.tsx
  src/app/sleep-tracker/page.tsx
  src/app/task-manager/page.tsx
  src/components/bar-line-chart.tsx
  src/components/dashboard.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/habit-heatmap.tsx
  src/components/header.tsx
  src/components/health-dashboard.tsx
  src/components/heatmap.tsx
  src/components/journal/journal.tsx
  src/components/profile-dropdown.tsx
  src/components/profile/delete-account.tsx
  src/components/profile/modify-account-info.tsx
  src/components/profile/modify-password.tsx
  src/components/sleep-entry.tsx
  src/components/tasks/task-manager.tsx
  src/components/ui/line-graph.tsx
  src/components/water-chart.tsx
Labels: ui updates

#152 Add unit tests for Supabase client creation and cookie handling
  src/tests/unit/server.spec.ts
Labels: QA/Testing

#151 Fix longer tasks overflowing div
  src/components/tasks/task-manager.tsx
Labels: bug fix

#157 Fix cooking scale
  src/components/data-intake/data-intake-form.tsx
  src/components/data-intake/yes-no-form.tsx
Labels: bug fix

#158 Cu/xx/update colours
  src/app/home/page.tsx
  src/app/page.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/header.tsx
  src/components/journal/journal.tsx
  src/components/path-morphing-nav.tsx
  src/components/profile/delete-account.tsx
  src/components/profile/modify-account-info.tsx
  src/components/profile/modify-password.tsx
  src/components/reminder-card.tsx
  src/components/ui/floating-shapes.tsx
Labels: ui updates

#160 updated fonts for new graph, modified console.logs
  src/app/home/page.tsx
  src/components/add-habit-charts.tsx
  src/lib/email-service.ts
Labels: ui updates

#161 Hk/test/acceptance testing
  src/actions/tasks.ts
  src/components/journal/journal.tsx
  src/components/path-morphing-nav.tsx
  src/components/profile/modify-account-info.tsx
  src/components/profile/modify-password.tsx
  src/components/ui/floating-shapes.tsx
  src/tests/acceptance/Acceptance Testing.md
Labels: QA/Testing

#163 Small UI Changes
  src/app/sleep-tracker/page.tsx
  src/components/add-habit-charts.tsx
  src/components/bar-line-chart.tsx
  src/components/sleep-chart.tsx
  src/components/sleep-entry.tsx
  src/components/water-chart.tsx
Labels: ui updates

#164 Add comments
  src/actions/ai-data-analysis.ts
  src/actions/ai-fetch.ts
  src/actions/data-visualization.ts
  src/app/home/page.tsx
  src/app/page.tsx
  src/components/ai-response.tsx
  src/components/health-dashboard.tsx
  src/components/home-animation.tsx
  src/components/mood-bar.tsx
  src/components/mood-flow.tsx
  src/components/particles.tsx
  src/components/path-morphing-nav.tsx
  src/components/ui/line-graph.tsx
Labels: documentation

#173 Cleanup supabase calls
  src/actions/auth.ts
  src/actions/data-intake.ts
  src/app/daily-intake/page.tsx
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/reminders/page.tsx
  src/app/sleep-tracker/page.tsx
  src/app/task-manager/page.tsx
  src/components/journal/journal.tsx
  src/tests/unit/auth.spec.ts
Labels: enhancement

#174 Hk/xx/remove dark css
  src/app/home/page.tsx
  src/app/page.tsx
  src/components/ai-response.tsx
  src/components/dashboard.tsx
  src/components/habit-heatmap.tsx
  src/components/heatmap.tsx
  src/components/journal/journal.tsx
  src/components/path-morphing-nav.tsx
Labels: ui updates

#176 reset password link only sends to valid emails
  package-lock.json
  src/actions/auth.ts
  src/app/page.tsx
  src/tests/unit/auth.spec.ts
  src/tests/unit/sleep-tracker.spec.ts
Labels: bug fix

#177 Add responsive navigation handling to Header and ProfileDropdown components
  src/components/header.tsx
  src/components/profile-dropdown.tsx
  src/components/tasks/task-manager.tsx
Labels: ui updates

#179 Ap/change docker image name
  .github/workflows/docker-image.yml
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  src/actions/tasks.ts
Labels: QA/Testing

#181 Add load testing script for Ollama API with concurrent requests
  llm-api/load_testing/ai_llm_load_test.py
  llm-api/load_testing/load_test_report.txt
Labels: QA/Testing

#183 Ap/docker image.yml bug fix
  .github/workflows/docker-image.yml
  README.md
Labels: bug fix

#184 Hk/UI/mobile responsive dashboard
  src/app/daily-intake/page.tsx
  src/app/home/page.tsx
  src/app/journal/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/reminders/page.tsx
  src/app/reset-password/page.tsx
  src/app/sleep-tracker/page.tsx
  src/app/task-manager/page.tsx
  src/components/journal/journal.tsx
  src/components/layout/footer.tsx
  src/components/layout/header.tsx
  src/components/layout/profile-dropdown.tsx
  src/components/login-page/feature-section.tsx
  src/components/login-page/task-manager-mock.tsx
  src/components/magicui/fireworks.tsx
  src/components/quick-links.tsx
  src/components/reminders/reminder-card.tsx
Labels: ui updates

#186 Mg/test/set up load testing
  artillery.yml
  middleware.ts
  package-lock.json
  package.json
  src/components/profile/delete-account.tsx
  src/tests/integration/email-integration.spec.ts
  src/tests/load/artillery/signup.ts
  src/tests/load/commands/login.ts
  src/tests/load/commands/signup.ts
Labels: QA/Testing

#187 Add animations to sleep entry and reminder
  artillery.yml
  src/app/error/page.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/data-intake/add-habit.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/data-intake/quantity-tracker.tsx
  src/components/data-intake/sleep-entry.tsx
  src/components/data-intake/yes-no-form.tsx
  src/components/data-visualization/add-habit-charts.tsx
  src/components/data-visualization/ai-response.tsx
  src/components/data-visualization/bar-line-chart.tsx
  src/components/data-visualization/health-dashboard.tsx
  src/components/data-visualization/heatmap.tsx
  src/components/data-visualization/line-graph.tsx
  src/components/data-visualization/mood-bar.tsx
  src/components/data-visualization/mood-flow.tsx
  src/components/data-visualization/sleep-chart.tsx
  src/components/journal/journal.tsx
  src/components/journal/random-prompt-card.tsx
  src/components/layout/header.tsx
  src/components/layout/profile-dropdown.tsx
  src/components/layout/quick-links.tsx
  src/components/login-page/reset-password.tsx
  src/components/login-page/task-manager-mock.tsx
  src/components/magicui/confetti.tsx
  src/components/profile/delete-account.tsx
  src/components/profile/modify-account-info.tsx
  src/components/profile/modify-password.tsx
  src/components/reminders/reminder-card.tsx
  src/components/shadcn/badge.tsx
  src/components/shadcn/button.tsx
  src/components/shadcn/calendar.tsx
  src/components/shadcn/card.tsx
  src/components/shadcn/checkbox.tsx
  src/components/shadcn/dialog.tsx
  src/components/shadcn/dropdown-menu.tsx
  src/components/shadcn/input.tsx
  src/components/shadcn/label.tsx
  src/components/shadcn/progress.tsx
  src/components/shadcn/radio-group.tsx
  src/components/shadcn/scroll-area.tsx
  src/components/shadcn/select.tsx
  src/components/shadcn/separator.tsx
  src/components/shadcn/switch.tsx
  src/components/shadcn/tabs.tsx
  src/components/shadcn/textarea.tsx
  src/components/shadcn/toggle-group.tsx
  src/components/shadcn/toggle.tsx
  src/components/shadcn/tooltip.tsx
  src/components/tasks/task-manager.tsx
  src/components/ui/counter-card.tsx
  src/components/ui/particles-background.tsx
Labels: ui updates

#188 Updated the toast and other misc UI components:
  .prettierrc
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/data-intake/sleep-entry.tsx
  src/components/data-visualization/add-habit-charts.tsx
  src/components/data-visualization/bar-line-chart.tsx
  src/components/data-visualization/mood-bar.tsx
  src/components/data-visualization/mood-flow.tsx
  src/components/data-visualization/sleep-chart.tsx
  src/components/data-visualization/water-chart.tsx
  src/components/layout/header.tsx
  src/components/layout/profile-dropdown.tsx
  src/components/login-page/reset-password.tsx
  src/components/profile/modify-account-info.tsx
  src/components/profile/modify-password.tsx
  src/components/reminders/reminder-card.tsx
Labels: ui updates, QA/Testing

#193 cu/xx/journal load testing
  .gitignore
  package-lock.json
  package.json
  src/tests/load/artillery/load.ts
  src/tests/load/commands/test-data-visualization.ts
  src/tests/load/commands/test-journal.ts
  src/tests/load/commands/test-login.ts
  test-results/.last-run.json
Labels: QA/Testing

#194 cu/XX/update-file-names
  src/app/api/cron/route.ts
  src/app/daily-habits/page.tsx
  src/app/home/page.tsx
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/sleep-tracker/page.tsx
  src/app/task-manager/page.tsx
  src/components/data-intake/add-habit-dialog.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/data-intake/quantity-tracker.tsx
  src/components/data-intake/sleep-entry-card.tsx
  src/components/data-visualization/animated-line-graph.tsx
  src/components/data-visualization/habit-line-charts.tsx
  src/components/data-visualization/heatmap.tsx
  src/components/data-visualization/mood-flow.tsx
  src/components/data-visualization/water-chart.tsx
  src/components/journal/random-prompt-card.tsx
  src/components/layout/header.tsx
  src/components/layout/quick-links.tsx
  src/components/login-page/path-drawing.tsx
  src/components/login-page/task-manager-mockup.tsx
  src/components/profile/modify-account.tsx
  src/components/ui/counter.tsx
  src/lib/email-templates.ts
Labels: ui updates, QA/Testing

#198 Create test-reminders-results.txt
  src/tests/load/test-results/test-reminders-results.txt
Labels: QA/Testing

#199 update reminders results file
  src/tests/load/test-results/test-reminders-results.txt
Labels: QA/Testing

#195 Cn/test/load intake
  artillery.yml
  src/tests/load/artillery/load.ts
  src/tests/load/commands/test-daily-data.ts
  src/tests/load/commands/test-sleep.ts
Labels: QA/Testing

#203 Fix tooltip logic on heatmap
  README.md
  src/components/data-visualization/heatmap.tsx
Labels: bug fix

#205 cu/xx/update load test url
  src/tests/load/commands/test-daily-data.ts
  src/tests/load/test-results/test-daily-data-results.txt
Labels: QA/Testing

#206 Develop
  src/tests/load/commands/test-daily-data.ts
  src/tests/load/test-results/test-daily-data-results.txt
Labels: release
