Repository Mind-Garden/mind-garden, pull requests merged in 2025-04, with the labels that each got.

#208 fix dates that were causing tests to fail
  src/tests/integration/data-visualization-integration.spec.ts
Labels: QA/Testing

#209 Add UI animations for daily data intake
  README.md
  src/components/data-intake/data-intake-form.tsx
Labels: enhancement

#210 Update minor UI
  src/app/page.tsx
  src/components/data-intake/yes-no-form.tsx
  src/components/tasks/task-manager.tsx
  src/components/ui/counter.tsx
Labels: ui updates

#213 cu/xx/update logos
  public/logo-black-line.png
  public/logo-blue.png
  public/logo-grad-line.png
  src/app/favicon.ico
  src/app/page.tsx
  src/components/layout/header.tsx
Labels: ui updates

#214 Mg/UI/reset password
  src/components/login-page/reset-password.tsx
Labels: ui updates

#212 Cn/UI/add habit card
  src/app/home/page.tsx
  src/components/data-intake/add-habit-dialog.tsx
  src/components/data-intake/quantity-tracker.tsx
  src/components/data-intake/yes-no-form.tsx
  src/components/data-visualization/heatmap.tsx
Labels: ui updates

#215 Update water chart with analytics
  src/app/home/page.tsx
  src/components/data-visualization/water-chart.tsx
Labels: ui updates

#216 Fix date reference in water intake calculation
  src/components/data-visualization/water-chart.tsx
Labels: bug fix

#218 Mg/UI/sleep chart
  src/actions/ai-data-analysis.ts
  src/components/data-intake/sleep-entry-card.tsx
  src/components/data-visualization/ai-response.tsx
  src/components/data-visualization/bar-line-chart.tsx
  src/components/data-visualization/health-dashboard.tsx
  src/components/data-visualization/sleep-chart.tsx
  src/components/reminders/reminder-card.tsx
  src/lib/utils.ts
  src/tests/unit/data-summarization.spec.ts
  src/tests/unit/lib-utils.spec.ts
Labels: enhancement, ui updates

#217 Update moodbar ui
  package-lock.json
  src/components/data-intake/scale-icon.tsx
  src/components/data-visualization/health-dashboard.tsx
  src/components/data-visualization/mood-bar.tsx
  src/components/data-visualization/mood-flow.tsx
  src/components/tasks/task-manager.tsx
  src/lib/time.ts
  src/supabase/schema.ts
  src/tests/unit/time.spec.ts
Labels: enhancement, ui updates

#220 Develop
  README.md
  package-lock.json
  public/gradient.svg
  public/logo-black-line.png
  public/logo-blue.png
  public/logo-grad-line.png
  public/logo.png
  src/actions/ai-data-analysis.ts
  src/app/favicon.ico
  src/app/home/page.tsx
  src/app/page.tsx
  src/components/data-intake/add-habit-dialog.tsx
  src/components/data-intake/data-intake-form.tsx
  src/components/data-intake/quantity-tracker.tsx
  src/components/data-intake/scale-icon.tsx
  src/components/data-intake/sleep-entry-card.tsx
  src/components/data-intake/yes-no-form.tsx
  src/components/data-visualization/ai-response.tsx
  src/components/data-visualization/bar-line-chart.tsx
  src/components/data-visualization/health-dashboard.tsx
  src/components/data-visualization/heatmap.tsx
  src/components/data-visualization/mood-bar.tsx
  src/components/data-visualization/mood-flow.tsx
  src/components/data-visualization/sleep-chart.tsx
  src/components/data-visualization/water-chart.tsx
  src/components/layout/header.tsx
  src/components/login-page/reset-password.tsx
  src/components/reminders/reminder-card.tsx
  src/components/tasks/task-manager.tsx
  src/components/ui/counter.tsx
  src/lib/time.ts
  src/lib/utils.ts
  src/supabase/schema.ts
  src/supabase/scripts/tables.sql
  src/tests/integration/data-visualization-integration.spec.ts
  src/tests/unit/data-summarization.spec.ts
  src/tests/unit/lib-utils.spec.ts
  src/tests/unit/time.spec.ts
Labels: release
